version: "3.8"

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: fastapi_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123!
    ports:
      - "3307:3306"
    volumes:
      # - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - fastapi_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "dev",
          "-pdev123!",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  # FastAPI Application
  web:
    build: .
    container_name: fastapi_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3307
      - DATABASE_USER=dev
      - DATABASE_PASSWORD=dev123!
      - DATABASE_NAME=testdb
      - DEBUG=true
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fastapi_network
    volumes:
      # Mount source code for development (comment out for production)
      - ./app:/app/app
      - ./test_connection.py:/app/test_connection.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # phpMyAdmin (optional - for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fastapi_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3307
      PMA_USER: dev
      PMA_PASSWORD: dev123!
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge

volumes:
  mysql_data:
