version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: fastapi_mysql_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: testdb
      MYSQL_USER: dev
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    ports:
      - "127.0.0.1:3306:3306"  # Bind to localhost only
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./mysql.conf:/etc/mysql/conf.d/mysql.conf:ro
    networks:
      - fastapi_network
    secrets:
      - mysql_root_password
      - mysql_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # FastAPI Application
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: fastapi_app_prod
    restart: always
    ports:
      - "127.0.0.1:8000:8000"  # Bind to localhost only
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=dev
      - DATABASE_NAME=testdb
      - DEBUG=false
      - SECRET_KEY_FILE=/run/secrets/secret_key
    env_file:
      - .env.prod
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fastapi_network
    secrets:
      - mysql_password
      - secret_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: fastapi_nginx_prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - web
    networks:
      - fastapi_network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  fastapi_network:
    driver: bridge
    internal: false

volumes:
  mysql_data:
    driver: local
  nginx_logs:
    driver: local

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_password:
    file: ./secrets/mysql_password.txt
  secret_key:
    file: ./secrets/secret_key.txt
